name: Deploy gschneiderdev Media Links

on:
  push:
    branches:
      - main

jobs:
  deploy_on_GithubPages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_DEPLOY }}
          publish_dir: .
          enable_jekyll: false
          force_orphan: true
          # If your site is inside a subfolder (e.g. /dist), change publish_dir accordingly.
